config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users
  resources :payments
  resources :order_items
  resources :orders
  resources :line_items
  resources :carts
  resources :support_requests, only: [ :index, :update ]

  root "products#index"
  put "/line_items_dec", to: "line_items#decrease", as: "line_items_dec"
  get "/success", to: "orders#success", as: "orders_success"

  resources :products
  

  # get "/products", to: "products#index"
  # get "/products/:id", to: "products#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    validates :product_name, presence: true, uniqueness: true
    validates :description, presence: true, length: { minimum: 10 }
    validates :price, presence: true, numericality:{ greater_than: 0, message: "Price should be numerical greater than 0"}
    validates :vendor, presence: true
    validates :image, presence: true
    has_one_attached :image
    has_many :line_items
    before_destroy :ensure_not_referenced_by_any_line_item

    private
    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
            throw :abort
        end
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include VisitCounter
  before_action :set_counter, only: [:index]
  before_action :authenticate_user!
  def index
    @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end
  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path
  end
 
  private
    def product_params
      params.require(:product).permit(:product_name, :description, :price, :vendor, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
  <div>
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
    <% @product.errors.full_messages_for(:product_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @product.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
    <% @product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :vendor %><br>
    <%= form.text_field :vendor %>
    <% @product.errors.full_messages_for(:vendor).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
    <% @product.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Products</h1>


<div data-controller="hello" data-hello-url-value=<%= line_items_path %> data-hello-count-value=<%= Cart.quantity_count session[:cart_id] %> class="image-container"  >
  <% @products.each do |product| %>
    <div class="item-image">
    <div class="pinImage">
   
      <%= link_to image_tag(product.image), product %>
      
     
      
      
    
      </div>
      <%= link_to product.product_name, product %>
      
      
      
      
      <button data-action="hello#addToCart" data-session="<%=(session[:cart_id]) ? Cart.find(session[:cart_id]).line_items.sum { |x| x['quantity']} : 0 %>" id='<%=product.id%>'>add to cart</button>
      
    </div>
    
    
  <% end %>
  <div>Cart count</div>
  <div data-hello-target="cart"><%=(session[:cart_id]) ? Cart.find(session[:cart_id]).line_items.sum { |x| x['quantity']} : 0 %></div>
</div>

<%=Cart.quantity_count session[:cart_id] %>
<%= link_to "New Product", new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<%= image_tag(@product.image,style:("width:450px;height:550px")) %>
<h1><%= @product.product_name %></h1>
<p><%= @product.description %></p>
<h3><span>&#8377;</span><%= number_to_currency(@product.price,format:"%n") %></h3>
<p><%= @product.vendor %></p>


<ul>
  <li><%= link_to "Edit", edit_product_path(@product) %></li>
  <li><%= link_to "Destroy", product_path(@product),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>